{{- if .Values.awsSecurityGroupPolicies.enabled -}}
{{- range .Values.awsSecurityGroupPolicies.policies -}}
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: {{ .name }}
  namespace: {{ template "jenkins.namespace" $ }}
spec:
  podSelector: 
    {{- toYaml .podSelector | nindent 6}}
  securityGroups:
    groupIds: 
    {{- toYaml .securityGroupIds | nindent 6}}
---
{{- end -}}
{{- end -}}
